services:

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: ai-mlflow

    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --allowed-hosts "ai-mlflow,ai-mlflow:5000,localhost,localhost:5000,192.168.182.181"
      --backend-store-uri
      postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ai-postgres:5432/${MLFLOW_DB}
      --artifacts-destination
      /mlflow-artifacts

    ports:
      - "${MLFLOW_PORT}:5000"

    volumes:
      - mlflow_artifacts:/mlflow-artifacts

    networks:
      - ai-lab

    restart: unless-stopped

volumes:

  mlflow_artifacts:


networks:

  ai-lab:
    external: true
